# Trading Desk 5.0 - Cloud Build Configuration
#
# Usage:
#   Triggered by push:  Automatic (COMMIT_SHA populated by Cloud Build)
#   Manual deploy:      gcloud builds submit --substitutions=_TAG=$(git rev-parse --short HEAD)
#   Quick deploy:       gcloud run deploy trading-desk --source .
#
# Deploys to: Cloud Run (us-east1)

substitutions:
  # _TAG is used for manual builds; COMMIT_SHA is used for triggered builds
  # Default to 'manual' if neither is provided (shouldn't happen in practice)
  _TAG: 'manual'

steps:
  # Build the container image
  # Use COMMIT_SHA if available (triggered build), otherwise use _TAG (manual build)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG="${COMMIT_SHA:-${_TAG}}"
        docker build -t gcr.io/$PROJECT_ID/trading-desk:$$TAG -t gcr.io/$PROJECT_ID/trading-desk:latest .

  # Push the container images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG="${COMMIT_SHA:-${_TAG}}"
        docker push gcr.io/$PROJECT_ID/trading-desk:$$TAG
        docker push gcr.io/$PROJECT_ID/trading-desk:latest

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG="${COMMIT_SHA:-${_TAG}}"
        gcloud run deploy trading-desk \
          --image gcr.io/$PROJECT_ID/trading-desk:$$TAG \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          # SECURITY: --allow-unauthenticated is required because Telegram webhooks
          # need public HTTP access to POST /telegram. All sensitive endpoints
          # enforce API key authentication at the application level (verify_api_key).
          # The Telegram webhook validates X-Telegram-Bot-Api-Secret-Token header.
          # See src/main.py: verify_api_key() and verify_telegram_secret().
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 3 \
          --timeout 300 \
          --set-secrets 'SECRETS=trading-desk-secrets:latest' \
          --set-env-vars 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCS_BUCKET=your-gcs-bucket'

images:
  - 'gcr.io/$PROJECT_ID/trading-desk:latest'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
