# Trading Desk 5.0 - Cloud Build Configuration
# Triggers: Push to main branch
# Deploys to: Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-desk:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-desk:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trading-desk:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trading-desk:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trading-desk'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trading-desk:$COMMIT_SHA'
      - '--region'
      - 'us-east1'  # Close to NYSE
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # For Telegram webhook
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '300'
      - '--set-secrets'
      - 'SECRETS=trading-desk-secrets:latest'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCS_BUCKET=your-gcs-bucket'

images:
  - 'gcr.io/$PROJECT_ID/trading-desk:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/trading-desk:latest'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
